// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTS-z5TTKhK1PvVNVw9wqhYIpUesb4GE',
    appId: '1:576815895335:web:5ef69a4e7e548c011fcf02',
    messagingSenderId: '576815895335',
    projectId: 'crookwatch-e4c75',
    authDomain: 'crookwatch-e4c75.firebaseapp.com',
    storageBucket: 'crookwatch-e4c75.firebasestorage.app',
    measurementId: 'G-RLWXJFSWFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1sfV62BnVKg8ts9eTxgii9hH5Kz27rHs',
    appId: '1:576815895335:android:d5299e7d26b4952d1fcf02',
    messagingSenderId: '576815895335',
    projectId: 'crookwatch-e4c75',
    storageBucket: 'crookwatch-e4c75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkAl2llFMFMwvDXoSwl9Ew3EWH6wIp2qQ',
    appId: '1:576815895335:ios:e0b666d0097e33d41fcf02',
    messagingSenderId: '576815895335',
    projectId: 'crookwatch-e4c75',
    storageBucket: 'crookwatch-e4c75.firebasestorage.app',
    iosBundleId: 'com.example.crookwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkAl2llFMFMwvDXoSwl9Ew3EWH6wIp2qQ',
    appId: '1:576815895335:ios:e0b666d0097e33d41fcf02',
    messagingSenderId: '576815895335',
    projectId: 'crookwatch-e4c75',
    storageBucket: 'crookwatch-e4c75.firebasestorage.app',
    iosBundleId: 'com.example.crookwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjTS-z5TTKhK1PvVNVw9wqhYIpUesb4GE',
    appId: '1:576815895335:web:dcccfab90fe6e43c1fcf02',
    messagingSenderId: '576815895335',
    projectId: 'crookwatch-e4c75',
    authDomain: 'crookwatch-e4c75.firebaseapp.com',
    storageBucket: 'crookwatch-e4c75.firebasestorage.app',
    measurementId: 'G-H7Z440NK3S',
  );
}
